# Generated by Django 6.1.1 on 2026-10-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_projectfile_remove_project_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Файл проекта', 'verbose_name_plural': 'Файлы проектов'},
        ),
    ]
