# Generated by Django 6.1.1 on 2026-10-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_alter_tag_options_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='data_file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
    ]
